version: '3'

services:
  frontend_app:
    container_name: 
      fidelizoume_frontend
    build: 
      ./frontend/
    command: 
      npm run start
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./frontend:/usr/app
      - /usr/app/node_modules
    expose:
      - 3000
    ports:
      - "3000:3000"

  backend_app:
    container_name: 
        fidelizoume_backend
    build: 
      ./backend/
    ports:
      - "3001:3001"